### ISSUE TITLE
post/put and json request data

### ISSUE THREAD

**Issue by bradbishop** [mkumatag/openbmc-automation#12]
To get post to work with openbmc post request I had to do this:

/org/openbmc/records/events/action/accepttestmessage ( this is a no-argument method )

${data}=    convert to string    { "data": [] }

I'm assuming there is a better way.  I imagine put has the same problem.  As things are right now...nothing goes to the server at all.  To see exactly what the server is getting you can add this line to JsonApiRequestPlugin::validate_request (/usr/sbin/obmc-rest):

print request.body.getvalue()

Restart it like this:  systemctl stop obmc-rest;  /usr/sbin/obmc-rest

With curl -k -X POST -H "Content-Type: application/json" -d "{ \"data\": [] }" https://192.168.253.191://org/openbmc/records/events/action/accepttestmessage

{ "data": [] }

With robot nothing is printed at all.

**Comment by mkumatag** [comment]
Now I remember the issue you are facing with the same code what I'm running.. If because of issue in robotframework-requests a library.. So you will have to upgrade to obotframework-requests>=0.3.9 or use tox which will install this from requirement file
