### ISSUE TITLE
Sleep in Host On sequence

### ISSUE THREAD

**Issue by tomjoseph83** [mkumatag/openbmc-automation#34]
Why do we need a 120 sec delay in the Host Power on Sequence? Once the Host is booted the test suite can be run?

Host PowerOn
    [Documentation]     Keyword to poweron the host and wait till boot up
    ${chassis_uri}=     Get Chassis URI
    Should Not Be Empty     ${chassis_uri}      msg=Failed to get the chassis URI in the openbmc machine
    ${data}=    create dictionary   data=@{EMPTY}
    ${resp}=    openbmc post request     ${chassis_uri}/action/powerOn      data=${data}
    Wait For Host To Bootup
    Sleep   120sec

**Comment by mkumatag** [comment]
I'm using this keyword in test_occ_powercap.robot where I was using occ and powercap which will take some time to get updated after the host boot, so added 2 min delay to make sure these fields are updated with proper values.
