### ISSUE TITLE
network tests cause all systems to have the same mac

### ISSUE THREAD

**Issue by causten** [mkumatag/openbmc-automation#42]
I think the testing of setting a mac address is wrong.  It needs to save off the existing mac value prior to testing so it can be restored. I ran the test suite on different machines, now they both have the same mac.

**Comment by ratagupt** [comment]
Sure,I will correct it

**Comment by causten** [comment]
Can this get some focus, robot is broken without it

**Comment by ratagupt** [comment]
Hi Chris,
 
Please use the following pull request to make it work.
 
https://github.com/mkumatag/openbmc-automation/pull/47
 
Regards
Ratan Gupta
 
 
----- Original message -----From: Chris Austen notifications@github.comTo: mkumatag/openbmc-automation openbmc-automation@noreply.github.comCc: Ratan K Gupta/India/IBM@IBMIN, Comment comment@noreply.github.comSubject: Re: [mkumatag/openbmc-automation] network tests cause all systems to have the same mac (#42)Date: Fri, Apr 29, 2016 7:24 AM 
Can this get some focus, robot is broken without it

**Comment by mkumatag** [comment]
Fixed part of https://github.com/mkumatag/openbmc-automation/pull/49 by @ratagupt.
