### ISSUE TITLE
PreTag Set the Boot Device as Default using ipmitool - FAILURE

### ISSUE THREAD

**Issue by gkeishin** [mkumatag/openbmc-automation#59]
There are other failure related to execution of the ipmi tool in the test run seen during testing.  

Looking into the test code and the o/p we can see that there is a piece of code in ipmi library code that needs to be modified or amend to the existing code .. ( Code change snapshot at the end of the mail )

For Example in the test case... 

Set the Boot Device as Default using ipmitool  --> calls Execute Command and sets the o/p for the REST operation ahead.. however if this Execution returns errors we are not catching in the code..

The failure is caught down stream and not here for execution of the IPMI command

Should Be Equal ${OUTPUT}, ${args}
Documentation:  

Fails if the given objects are unequal.
Start / End / Elapsed:  20160530 10:06:50.038 / 20160530 10:06:50.039 / 00:00:00.001
10:06:50.038    INFO    Argument types are:
<type 'dict'>
<type 'unicode'>  
10:06:50.039    FAIL    {u'description': u'Internal Server Error', u'exception': u"DBusException('The name :1.8 was not provided by any .service files',)", u'traceback': [u'Traceback (most recent call last):', u'  File "/usr/lib/python2.7/site-packages/bottle.py", line 858, in _handle', u'    route, args = self.router.match(environ)', u'  File "/usr/sbin/obmc-rest", line 746, in custom_router_match', u'    route.callback._setup(**args)', u'  File "/usr/sbin/obmc-rest", line 86, in _setup', u'    return self.setup(**kw)', u'  File "/usr/sbin/obmc-rest", line 271, in setup', u"    request.route_data['obj'] = self.find(path, prop)", u'  File "/usr/sbin/obmc-rest", line 258, in find', u'    self.app.instance_handler.setup(path)', u'  File "/usr/sbin/obmc-rest", line 366, in setup', u"    request.route_data['map'] = self.find(path, callback)", u'  File "/usr/sbin/obmc-rest", line 357, in find', u'    path=path)}', u'  File "/usr/sbin/obmc-rest", line 103, in try_mapper_call', u'    return f(**kw)', u'  File "/usr/lib/python2.7/site-packages/obmc/mapper.py", line 37, in get_object', u'    return self.iface.GetObject(path)', u'  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__', u'    **keywords)', u'  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking', u'    message, timeout)', u'DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.8 was not provided by any .service files']} != Default

When the failure starts at the beginning of the test case itself, we should throw error and not continue.

Documentation:  Executes `command` on the remote machine and returns its outputs.
Start / End / Elapsed:  20160530 10:06:47.082 / 20160530 10:06:48.284 / 00:00:01.202
10:06:47.083    INFO    Executing command '/tmp/ipmitool -I dbus raw 0x0 0x8 0x05 0x80 0x00 0x00 0x00 0x00'.  
10:06:48.283    INFO    Command exited with return code 1.  
10:06:48.283    INFO    ${output} = 

The reason being the command execution error is not caught earlier at library   ./lib/ipmi_client.robot

Run IPMI Command
    [arguments]    ${args}
    ${output}=  Execute Command    /tmp/ipmitool -I dbus raw ${args}  
    Should Be Empty     ${stderr}
    set test variable    ${OUTPUT}     "${output}"

The new should be

Run IPMI Command
    [arguments]    ${args}
    ${output}   ${stderr}=  Execute Command    /tmp/ipmitool -I dbus raw ${args}  return_stderr=True
    Should Be Empty     ${stderr}
    set test variable    ${OUTPUT}     "${output}"

o/p  - SUCCESS 

Documentation:  Executes `command` on the remote machine and returns its outputs.
Start / End / Elapsed:  20160530 13:20:56.478 / 20160530 13:20:59.134 / 00:00:02.656
13:20:56.479    INFO    Executing command '/tmp/ipmitool -I dbus raw 0x0 0x8 0x05 0x80 0x00 0x00 0x00 0x00'.  
13:20:59.133    INFO    Command exited with return code 0.  
13:20:59.134    INFO    ${output} =  
13:20:59.134    INFO    ${stderr} = 

o/p - On FAILURE ( fake test )

Documentation:  Executes `command` on the remote machine and returns its outputs.
Start / End / Elapsed:  20160530 13:37:14.695 / 20160530 13:37:16.528 / 00:00:01.833
13:37:14.695    INFO    Executing command '/tmp/ipmitool -I dbus raw 0xF1 0x8 0x05 0x80 0x00 0x00 0x00 0x00'.  
13:37:16.527    INFO    Command exited with return code 1.  
13:37:16.528    INFO    ${output} =  
13:37:16.528    INFO    ${stderr} = Unable to send RAW command (channel=0x0 netfn=0x31 lun=0x0 cmd=0x8 rsp=0xc1): Invalid command

If this change make sense to all ?

**Comment by mkumatag** [comment]
@causten  , @rahulmah can you please have a look?

**Comment by sivassrr** [comment]
@rahulmah , Rahul as discussed,  Need similar implement as in ipmi_client.robot (which you had implemented).

**Comment by causten** [comment]
Interesting!  I was not aware that we could obtain stderr in that way.  I like the idea.  Go for the change.

**Comment by gkeishin** [comment]
Code pushed for review.. Thanks

**Comment by gkeishin** [comment]
Just a heads up... there are 34 good cases here with this library function all.. Changing in all the places wouldn't be a good idea .

Since this will take some time to think it through to come up with a better solution to encapsulate the review comment changes and the migration of this Repo is going to happen soon.. I would want to ABORT this push and push a new one with the new changes onto the NEW Repo... Let me know if anyone of you have concerns..

rango@ubuntu:~/openbmc-automation/tests$ grep -ri "Run IPMI Command" \* | wc -l
34 <-- 34 places if checks needs to be added on the caller side...

rango@ubuntu:~/openbmc-automation/tests$ grep -ri "Run IPMI Command" *
test_bootpolicy.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x00 0x00 0x00 0x00
test_bootpolicy.robot: Run IPMI command 0x0 0x8 0x05 0xC0 0x00 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x00 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x04 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x08 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x0C 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x14 0x00 0x00 0x00
test_boot.robot: Run IPMI command 0x0 0x8 0x05 0x80 0x18 0x00 0x00 0x00
test_sensors.robot: Run IPMI command 0x06 0x36
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x01 0x00 0x35 0x00 0x00 0x00 0x00 0x00 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x04 0x00 0x00 0x00 0x00 0x14 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x04 0x00 0x00 0x00 0x00 0x0e 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x02 0x00 0x00 0x00 0x00 0x00 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x01 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x04 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x02 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x80 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x00 0x00 0x80 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0xff 0x00 0x01 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x80 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x00 0x00 0x80 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0xff 0x00 0x01 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x40 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0xff 0x00 0x00 0x40 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x10 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x00 0x00 0x10 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0xa9 0x00 0x40 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x00 0x00 0x40 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x10 0x00 0x00 0x00 0x00 0x20 0x00
test_sensors.robot: Run IPMI command 0x04 0x30 ${x} 0x00 0x00 0x00 0x00 0x10 0x00 0x00 0x20 0x00

**Comment by gkeishin** [comment]
Chris, any input on this... 

I don't foresee value add to catch the error for a command execution at the test code level nor any meaningful sense.. since by nature of command line execution.. whatever we execute should not fail.. 

Should it fail we should catch at the source where we are really executing and not propagate.. we shouldn't compare this command line execution with the REST call since the context and the nature of output are of different behaviors and results.. 

Having said that, Now the only other thing we could do here is... revamp the Run IPMI command into READ and WRITE commands module for IPMI... For read return whatever and for write catch at the source... 

Let me know whats your thoughts on it...

**Comment by gkeishin** [comment]
The code is merged.... Thanks
